# Generated by Django 4.0 on 2021-12-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Не указано', max_length=20)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=15)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carbrand')),
            ],
        ),
    ]
