# Generated by Django 4.0 on 2021-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='full_name',
            field=models.CharField(default='Не указано', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15),
        ),
    ]
