# Generated by Django 4.0 on 2021-12-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_full_name_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='breed',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.carbrand'),
        ),
    ]
